version: '3.4'

services:
  emsbackend:
    image: emsbackend:dev
    container_name: emsbackend
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "emsbackend"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - /Users/petralinaru/Desktop/EnergyManagementSystem/emsbackend_devices:/app
      - /Users/petralinaru/Desktop/EnergyManagementSystem/emsbackend_devices:/src
      - /Users/petralinaru/vsdbg/vs2017u5:/remote_debugger:rw
      - /Users/petralinaru/.nuget/packages/:/root/.nuget/packages:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net6.0/emsbackend.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true