version: '3.4'

services:
  emsbackend:
    image: ${DOCKER_REGISTRY-}emsbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - db
    networks:
      - benetwork
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: SQLServer2
    environment:
        SA_USER: sa
        SA_PASSWORD: "A&VeryComplex123Password"
        ACCEPT_EULA: Y
    ports:
        - "1434:1433"
networks:
  benetwork:
    name: backend-network
    external: true