// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using emsbackend.Data;

#nullable disable

namespace emsbackend.Migrations
{
    [DbContext(typeof(DeviceAPIDbContext))]
    [Migration("20231101155348_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("emsbackend.Models.DeviceInstance", b =>
                {
                    b.Property<int>("ID_Dev_Inst")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Dev_Inst"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dev_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_Dev_Type")
                        .HasColumnType("int");

                    b.Property<string>("ID_User")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID_Dev_Inst");

                    b.HasIndex("ID_User");

                    b.ToTable("DeviceInstances");
                });

            modelBuilder.Entity("emsbackend.Models.DeviceType", b =>
                {
                    b.Property<int>("ID_Dev_Type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Dev_Type_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxPower")
                        .HasColumnType("int");

                    b.HasKey("ID_Dev_Type");

                    b.ToTable("DeviceTypes");
                });

            modelBuilder.Entity("emsbackend.Models.UserClone", b =>
                {
                    b.Property<string>("ID_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_User");

                    b.ToTable("UserClones");
                });

            modelBuilder.Entity("emsbackend.Models.DeviceInstance", b =>
                {
                    b.HasOne("emsbackend.Models.UserClone", "UserClone")
                        .WithMany("DeviceInstances")
                        .HasForeignKey("ID_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserClone");
                });

            modelBuilder.Entity("emsbackend.Models.DeviceType", b =>
                {
                    b.HasOne("emsbackend.Models.DeviceInstance", null)
                        .WithOne("DeviceType")
                        .HasForeignKey("emsbackend.Models.DeviceType", "ID_Dev_Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("emsbackend.Models.DeviceInstance", b =>
                {
                    b.Navigation("DeviceType");
                });

            modelBuilder.Entity("emsbackend.Models.UserClone", b =>
                {
                    b.Navigation("DeviceInstances");
                });
#pragma warning restore 612, 618
        }
    }
}
