version: '3.4'

services:
  emsbackend:
    image: ${DOCKER_REGISTRY-}emsbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9091:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - benetwork
networks:
  benetwork:
    name: backend-network
    external: true